services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=24w"
      - "--web.enable-admin-api"
    user: "1000:1000"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:latest
    user: '1000:1000'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    depends_on:
      - cadvisor
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command: 
    - cadvisor
    - --docker_only=true
    - --enable_metric=cpu,memory,shed,network,referenced_memory
    - --housekeeping_interval=100ms        # refresh rate
    - --max_housekeeping_interval=150ms    # max jitter allowed
    - --allow_dynamic_housekeeping=false   # disable adaptive throttling
    ports:
    - 9080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  swift:
    depends_on:
      - cadvisor
    build:
      context: ../swift
      tags:
        - bap/swift:latest
    ports:
      - '8080:8080'
    privileged: true
    volumes:
      - ../data:/data

  php-fpm:
    depends_on:
      - cadvisor
    build:
      context: ../php
      target: app
      tags:
        - bap/php-fpm:latest
    expose:
      - '9000'
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
    volumes:
      - ../data:/var/www/data:ro

  php-nginx:
    build:
      context: ../php
      target: web
      tags:
        - bap/php-nginx:latest
    ports:
      - '8000:80'
    depends_on:
      - php-fpm
      - cadvisor

volumes:
  grafana-storage: {}
