global:
  scrape_interval: 350ms
  # Interval at which rules are evaluated, default 1m
  evaluation_interval: 5s

scrape_configs:
- job_name: cadvisor
  metric_relabel_configs:
    - source_labels: ['name']
      target_label: 'container'
  static_configs:
    - targets:
      - cadvisor:8080
