global:
  scrape_interval: 100ms
  # Interval at which rules are evaluated, default 1m
  evaluation_interval: 5s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
