global:
  scrape_interval: 100ms
  # Interval at which rules are evaluated, default 1m
  evaluation_interval: 5s

scrape_configs:
  - job_name: swift
    static_configs:
      - targets:
        - swift:8080
